// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// align_one
Rcpp::List align_one(const std::string& pattern, const std::string& text, int smax, bool with_cigar);
RcppExport SEXP _genoaligner_align_one(SEXP patternSEXP, SEXP textSEXP, SEXP smaxSEXP, SEXP with_cigarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type text(textSEXP);
    Rcpp::traits::input_parameter< int >::type smax(smaxSEXP);
    Rcpp::traits::input_parameter< bool >::type with_cigar(with_cigarSEXP);
    rcpp_result_gen = Rcpp::wrap(align_one(pattern, text, smax, with_cigar));
    return rcpp_result_gen;
END_RCPP
}
// align_sw_one
Rcpp::List align_sw_one(const std::string& text, const std::string& pattern, int match, int mismatch, int gap_open, int gap_extend, bool with_cigar);
RcppExport SEXP _genoaligner_align_sw_one(SEXP textSEXP, SEXP patternSEXP, SEXP matchSEXP, SEXP mismatchSEXP, SEXP gap_openSEXP, SEXP gap_extendSEXP, SEXP with_cigarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type text(textSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< int >::type match(matchSEXP);
    Rcpp::traits::input_parameter< int >::type mismatch(mismatchSEXP);
    Rcpp::traits::input_parameter< int >::type gap_open(gap_openSEXP);
    Rcpp::traits::input_parameter< int >::type gap_extend(gap_extendSEXP);
    Rcpp::traits::input_parameter< bool >::type with_cigar(with_cigarSEXP);
    rcpp_result_gen = Rcpp::wrap(align_sw_one(text, pattern, match, mismatch, gap_open, gap_extend, with_cigar));
    return rcpp_result_gen;
END_RCPP
}
// msa_run_cpp
Rcpp::List msa_run_cpp(const std::vector<std::string>& seqs, const std::string& mode, int gc_def, int codon_refine, bool local_frame);
RcppExport SEXP _genoaligner_msa_run_cpp(SEXP seqsSEXP, SEXP modeSEXP, SEXP gc_defSEXP, SEXP codon_refineSEXP, SEXP local_frameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type seqs(seqsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< int >::type gc_def(gc_defSEXP);
    Rcpp::traits::input_parameter< int >::type codon_refine(codon_refineSEXP);
    Rcpp::traits::input_parameter< bool >::type local_frame(local_frameSEXP);
    rcpp_result_gen = Rcpp::wrap(msa_run_cpp(seqs, mode, gc_def, codon_refine, local_frame));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genoaligner_align_one", (DL_FUNC) &_genoaligner_align_one, 4},
    {"_genoaligner_align_sw_one", (DL_FUNC) &_genoaligner_align_sw_one, 7},
    {"_genoaligner_msa_run_cpp", (DL_FUNC) &_genoaligner_msa_run_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_genoaligner(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
