# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

align_one <- function(pattern, text, smax, with_cigar) {
    .Call(`_genoaligner_align_one`, pattern, text, smax, with_cigar)
}

align_sw_one <- function(text, pattern, match, mismatch, gap_open, gap_extend, with_cigar) {
    .Call(`_genoaligner_align_sw_one`, text, pattern, match, mismatch, gap_open, gap_extend, with_cigar)
}

msa_run_cpp <- function(seqs, mode, gc_def, codon_refine, local_frame) {
    .Call(`_genoaligner_msa_run_cpp`, seqs, mode, gc_def, codon_refine, local_frame)
}

